# Generated by Django 5.1.7 on 2025-04-09 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_task"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
    ]
