# Generated by Django 5.1.7 on 2025-04-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="created_by",
        ),
    ]
