# Generated by Django 5.1.7 on 2025-04-09 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_remove_task_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="text",
            new_name="projectname",
        ),
    ]
